# Generated by Django 4.2.7 on 2023-11-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=16, null=True)),
                ('zip_code', models.IntegerField(max_length=7, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('tel', models.IntegerField(null=True)),
                ('established_at', models.DateField(null=True)),
                ('capital_stock', models.FloatField(null=True)),
                ('representative_pos', models.CharField(max_length=50, null=True)),
                ('representative_name', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('remarks', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField()),
            ],
        ),
    ]
